### ISSUE TITLE
Configuration Changed - From string isn't backwards compatible

### ISSUE THREAD

**Issue by knoxberry** [LabVIEW-DCAF/Scaling#10] opened 2017-02-15 15:31 UTC
URGENT!!!

From string needs to support previous versions. Scale data types changed between previous version and current version.

**Comment by pollockm** [comment] 2017-02-15 15:51
Investigating now.  Should have a new package out an hour or two after reproducing.  Not reproduced yet.

**Comment by pollockm** [comment] 2017-02-15 15:54
@knoxberry - Can you please send me a configuration file that currently fails to load so I can test this properly?

**Comment by pollockm** [comment] 2017-02-15 15:56
...I don't see changes made to the To String method for the last 8 months.  We didn't bump the version.

Might be something in the typedef or the parent class, though.

**Comment by knoxberry** [comment] 2017-02-15 16:00
I think the issue is with the typedef of compatible types. When Boolean was added. I'll try to send you a configuration shortly. I'll have to remove customer specific information. I had to revert versions for it to work properly.

**Comment by pollockm** [comment] 2017-02-15 16:00
Looks like the breaking change was this one, then:  https://github.com/LabVIEW-DCAF/Scaling/commit/c7d9a264ee4d7e93d9bf8dbd3f609f6ef6181b31

**Comment by pollockm** [comment] 2017-02-15 16:06
@knoxberry  - That should fix it.  Can you give it a try on your end and let me know if you still see any issues?  I'll hold off on pushing the package out to VIPM until you can validate.

**Comment by pollockm** [comment] 2017-02-15 16:10
I'll post a package here shortly that you can try.

**Comment by pollockm** [comment] 2017-02-15 16:27
Here you go.
[ni_lib_dcaf_scaling_framework-1.0.9.27.zip](https://github.com/LabVIEW-DCAF/Scaling/files/777647/ni_lib_dcaf_scaling_framework-1.0.9.27.zip)

**Comment by pollockm** [comment] 2017-02-15 18:48
@knoxberry Success?  Fail?  I'd like to push this out to VIPM today if you validate that it works.  Others will be hit by that bug, and I'd like to minimize our exposure.

**Comment by knoxberry** [comment] 2017-02-16 08:25
This works. Thanks for the quick turnaround!

**Comment by pollockm** [comment] 2017-02-16 13:24
Great!  Closing.  Thanks for reporting the issue - let us know if you find anything else!

**Closed as completed by pollockm** 2017-02-16 13:24 UTC
Labels: bug
